In [1]:
import pandas as pd
from cleaning.preprocess import getMissingValuesContainingColsWithCountOrMsg
from cleaning.preprocess import handleMissingValues
from cleaning.preprocess import getNumberOfDuplicateRows
from cleaning.preprocess import removeDuplicateRows
from cleaning.preprocess import getNumericColumnNamesFromData
from cleaning.preprocess import getTableOfNumericalAndCategoricalColumnsInDataOrMsg
from cleaning.preprocess import getCategoricalColumnNamesFromData
from cleaning.utils import preprocessGetDuplicateRowsCountMessageIfAny
from cleaning.preprocess import applyScalingOnNumericalColumns

In [2]:
titanic = pd.read_csv("datasets\\raw\\titanic.csv")
iris = pd.read_csv("datasets\\raw\\iris.csv")
onlineRetail = pd.read_csv("datasets\\raw\\online_retail.csv", encoding = "latin")

In [3]:
titanic.head(1)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.25,NaN,S

In [4]:
iris.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [5]:
getMissingValuesContainingColsWithCountOrMsg(titanic)

  Column Name  Missing Count
0         Age            177
1       Cabin            687
2    Embarked              2

In [6]:
getMissingValuesContainingColsWithCountOrMsg(iris)

In [7]:
handleMissingValues(titanic,{"Age" : "Drop Column"})

,PassengerId,Survived,Pclass,Name,Sex,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,0,0,370376,7.7500,NaN,Q

In [8]:
getMissingValuesContainingColsWithCountOrMsg(titanic)

  Column Name  Missing Count
0       Cabin            687
1    Embarked              2

In [9]:
titanic['Cabin'] = titanic['Cabin'].fillna(titanic['Cabin'].mode()[0])

In [10]:
getMissingValuesContainingColsWithCountOrMsg(titanic)

  Column Name  Missing Count
0    Embarked              2

In [11]:
titanic.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       2
dtype: int64

In [12]:
getNumberOfDuplicateRows(onlineRetail)

np.int64(5268)

In [13]:
removeDuplicateRows(onlineRetail)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,12/9/2011 12:50,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,12/9/2011 12:50,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,12/9/2011 12:50,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,12/9/2011 12:50,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,12/9/2011 12:50,4.95,12680.0,France

In [14]:
getNumberOfDuplicateRows(onlineRetail)

np.int64(0)

In [15]:
titanic.head(1)

,PassengerId,Survived,Pclass,Name,Sex,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,1,0,A/5 21171,7.25,B96 B98,S

In [16]:
titanic.select_dtypes(include=['number']).columns.to_list()

['PassengerId', 'Survived', 'Pclass', 'SibSp', 'Parch', 'Fare']

In [17]:
titanic.select_dtypes(include=['object']).columns.to_list()

['Name', 'Sex', 'Ticket', 'Cabin', 'Embarked']

In [18]:
getNumericColumnNamesFromData(titanic)

['PassengerId', 'Survived', 'Pclass', 'SibSp', 'Parch', 'Fare']

In [19]:
iris.head(1)

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa

In [20]:
getNumericColumnNamesFromData(iris)

['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm']

In [21]:
titanic.select_dtypes(include=['object']).columns.to_list()

['Name', 'Sex', 'Ticket', 'Cabin', 'Embarked']

In [22]:
getCategoricalColumnNamesFromData(titanic)

['Name', 'Sex', 'Ticket', 'Cabin', 'Embarked']

In [23]:
iris.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [24]:
iris_without_categorical_col = iris.iloc[:, :-1]

In [25]:
iris_without_categorical_col

      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0      1            5.1           3.5            1.4           0.2
1      2            4.9           3.0            1.4           0.2
2      3            4.7           3.2            1.3           0.2
3      4            4.6           3.1            1.5           0.2
4      5            5.0           3.6            1.4           0.2
..   ...            ...           ...            ...           ...
145  146            6.7           3.0            5.2           2.3
146  147            6.3           2.5            5.0           1.9
147  148            6.5           3.0            5.2           2.0
148  149            6.2           3.4            5.4           2.3
149  150            5.9           3.0            5.1           1.8

[150 rows x 5 columns]

In [26]:
if(len(getCategoricalColumnNamesFromData(iris_without_categorical_col)) == 0): print('No Categorical Columns in Data!')

No Categorical Columns in Data!

In [27]:
getTableOfNumericalAndCategoricalColumnsInDataOrMsg(titanic)

  Numerical Column Names Categorical Column Names
0            PassengerId                     Name
1                  SibSp                      Sex
2                  Parch                   Ticket
3                   Fare                    Cabin
4                    NaN                 Embarked
5                    NaN                 Survived
6                    NaN                   Pclass

In [28]:
titanic['Pclass'].nunique()

3

In [30]:
titanic.head()

,PassengerId,Survived,Pclass,Name,Sex,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,1,0,A/5 21171,7.2500,B96 B98,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,0,0,STON/O2. 3101282,7.9250,B96 B98,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,0,0,373450,8.0500,B96 B98,S

In [33]:
titanic['Fare'].head()

0     7.2500
1    71.2833
2     7.9250
3    53.1000
4     8.0500
Name: Fare, dtype: float64

In [34]:
titanic[['Fare']].head()

      Fare
0   7.2500
1  71.2833
2   7.9250
3  53.1000
4   8.0500